### ISSUE TITLE
Change shape of legend entries

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#10]
**Expected behaviour**
A dropdown next to a layer added to the snapshot to change the shape between `circle`, `square` or `line`

**Current behaviour**
n/a

**Describe alternatives you've considered**
Editing the exported snapshot.json before upload.

**Comment by Joonalai** [comment]
Should there be another choise for `automatic`? Now it sets the legend shape based on type of the layer, so `automatic` could preserve that option.

**Comment by n0rdlicht** [comment]
Yes, to preserve the old option let's add automatic, so it's only an override option.
