### ISSUE TITLE
UI for keywords

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#15]
**Expected behaviour**
An interface to add, change or delete keywords for a snapshot before exporting.
Alternatively we could combine the keywords from the metadata of each chosen layer.

**Current behaviour**
Uses default from plugin template.

**Comment by Joonalai** [comment]
I would prefer using as much QGIS functionality as possible, so using the metadata of the layers sound good solution! However, there are mentions of vocabularies, that will not be exported as a part of keywords. Is that OK? Also I assume that we want to keep the keywords mentioned in the config as well?

So in this case the keywords will be:
```json
{"keywords": [
      "europe",
      "switzerland",
      "gemeindescan",
      "geodata",
      "keyword1",
      "keyword2",
      "keyword3",
      "keyword4",
      "keyword5",
      "keyword6"
]}
```
![image](https://user-images.githubusercontent.com/33314057/101131249-a7a4c400-360d-11eb-9172-7c337495f3a1.png)

**Comment by Joonalai** [comment]
Alternatively we could have keywords in UI for common keywords and then use layer metadata keywords in addition.
