### ISSUE TITLE
Expose template files for users

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#18]
**Expected behaviour**
Provide sample template/config files and a way to set a user defined one to use as a snapshot base.

**Current behaviour**
-

**Comment by n0rdlicht** [comment]
Might not be needed, if we implement #15, #20 and #19.

**Comment by Joonalai** [comment]
What is the status of this? Should it be implemented? It would be easy one (~10min) since the functionality already exists and only UI part has to be implemented.

**Comment by n0rdlicht** [comment]
I think it makes sense to have them exposed at a minimum to see which parts we should keep in the future :)
