### ISSUE TITLE
UI for setting snapshot license

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#19]
**Expected behaviour**
A dropdown to select the license of the snapshot. If licenses inside the metadata for a layer is set, add the license(s) to the resources when exporting.

**Current behaviour**
Uses default license from plugin template.

**Comment by Joonalai** [comment]
@n0rdlicht can you provide the list of licenses?

**Comment by n0rdlicht** [comment]
I think the QGIS presets for layer licenses are a good selection actually, if that is accessible to the plugin.

![QGIS layer licenses](https://user-images.githubusercontent.com/1425577/100071551-78d36480-2e3b-11eb-9730-13637ecc73bf.png)

**Comment by Joonalai** [comment]
Alright, I will use those and if they are not accessible easily, I just "copy" the list to the config or code.

**Comment by Joonalai** [comment]
So should layer licenses be part of `snapshot.licenses` and dropdown license should be `snapshot.license`?

**Comment by n0rdlicht** [comment]
I think we can drop the `snapshot.license` entry and add the chosen license to the `snapshot.licenses` array as a dictionary.

**Comment by Joonalai** [comment]
Alright, I'll add another entry `snapshot.resource.licenses`.

**Comment by n0rdlicht** [comment]
Do we have a url to link to? A typical entry looks like this
```js
{
  "name": "ODC-PDDL-1.0",
  "path": "http://opendatacommons.org/licenses/pddl/",
  "title": "Open Data Commons Public Domain Dedication and License v1.0"
}
```

Though only name is required here.

**Comment by Joonalai** [comment]
In the PR #30 I have setting where I manually searched the urls. But where do I get the short names from?
```python
licences = {
    'Creative Commons CC Zero': 'https://creativecommons.org/share-your-work/public-domain/cc0/',
    'Open Data Commons Public Domain Dedication and Licence': 'https://opendatacommons.org/licenses/pddl/',
    'Creative Commons Attribution 4.0': 'https://creativecommons.org/licenses/by/4.0/',
    'Open Data Commons Attribution License': 'https://opendatacommons.org/licenses/by/1-0/',
    'Creative Commons Attribution Share-Alike 4.0': 'https://creativecommons.org/licenses/by-sa/4.0/',
    'Open Data Commons Open Database License': 'https://opendatacommons.org/licenses/odbl/',
}
```

**Comment by n0rdlicht** [comment]
The spec links [here](https://opendefinition.org/licenses/api/) which seems to have a hosted json with Open Knowledge list of open licenses [here](https://licenses.opendefinition.org/licenses/groups/od.json).

**Comment by Joonalai** [comment]
Thanks! Now there are `license.url` and `license.type` Should these be renamed: `url`->`path`, `type` -> `name` and should new field `license.title` be added?

**Comment by n0rdlicht** [comment]
> Thanks! Now there are `license.url` and `license.type` Should these be renamed: `url`->`path`, `type` -> `name` and should new field `license.title` be added?

Title I would add for use in the interface. As for naming: not very consistent on the FD / OKNF side either so would stick with how it is :)

**Comment by Joonalai** [comment]
Alright, makes sense!
