### ISSUE TITLE
Use author from project metadata for maintainers

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#20]
**Expected behaviour**
Write author string from the QGIS project setting into the `maintainers` field of the datapackage.

**Current behaviour**
Uses the default from the plugin template.

**Comment by Joonalai** [comment]
What should be put into `maintainer,web` field?

```json
"maintainers": [
    {
      "web": "https://github.com/n0rdlicht/",
      "name": "Thorben Westerhuys"
    }
  ]
```

**Comment by n0rdlicht** [comment]
I think we should switch this to the currrent [spec](https://specs.frictionlessdata.io/data-package/#contributors) which only uses a contributors key and add an entry there with the role `author` and the name as `title` but no additional fields.
