### ISSUE TITLE
Shape square is exported as rectangle

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#21]
**Describe the bug**
Polygon layers get set as `rectangle` shape in the legend entries.

**To Reproduce**
1. Add a polygon layer to a snapshot
2. Export

**Expected behavior**
`shape` inside the views > spec > legend should be set to `square` instead.

**Desktop (please complete the following information):**
 - Plugin: 1.0
 - QGIS 3.16
 - Python: 3.8
 - OS: Fedora 32

**Comment by Joonalai** [comment]
@n0rdlicht so all mentions of 'rectangle' should now be 'square'?

**Comment by n0rdlicht** [comment]
jep :) didn't catch that back then, sorry for that.

**Comment by Joonalai** [comment]
No problem! :)
