### ISSUE TITLE
Test coverage report

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#33]
If possible with the current setup, we could add a test coverage badge to the project to indicate availability of tests and there current extend.

**Comment by n0rdlicht** [comment]
Other (rabbit hole) topic here: multi platform/version tests. The ci runner is currently based on ubuntu, right?
@loleg ran into an issue on fedora, where qgis is shipping without python support (see https://github.com/qgis/QGIS/issues/32135) for some reason.

**Comment by Joonalai** [comment]
The CI process uses ready made docker images so maybe one could make those images with different environments. I think that would be a matter of another issue. Anyway, I started running tests with LTR version in [another project](https://github.com/GispoCoding/FMI2QGIS) so I can add those here as well.
