### ISSUE TITLE
Make 0.2.0 release

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#40]
Create the final 0.2.0 release, based on [Milestone 0.2.0](https://github.com/cividi/spatial-data-package-export/milestone/2).

**Comment by n0rdlicht** [comment]
@Joonalai after merging PR #38 some of the tests seem to fail, could you quickly check? Thanks.

**Comment by Joonalai** [comment]
@n0rdlicht I will check that tomorrow.
