### ISSUE TITLE
Improve Legend Export

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#43]
**Expected behaviour**
Order of items in a symbol matches the order in `snapshot.view.spec.legend` as well as snapshot layer order (also see #9).

**Current behaviour**
Some exports produce "shuffled" entries in the legend array.

**Comment by LKajan** [comment]
Hi @n0rdlicht,
I have looked into the issue but couldn't find the problem at first glance.
Can you reproduce the issue? Could you please share your data and project file to reproduce the issue?

**Comment by n0rdlicht** [comment]
> Hi @n0rdlicht,
> I have looked into the issue but couldn't find the problem at first glance.
> Can you reproduce the issue? Could you please share your data and project file to reproduce the issue?

Currently trying to get my QGIS install to work. If I remember correctly it was the graduated ones that where usually out of order after the export. Will try to fix the setup and compile a sample for you.

**Comment by n0rdlicht** [comment]
Ok. Tried a couple of things that lead to this in the past, but also can't reproduce at the moment. Would suggest we close this and use the existing beta build to test existing installations for upgrade/compatibility issues to then do the full release. @Joonalai fine with you?
