### ISSUE TITLE
Output directory get's overwritten

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#53]
**Describe the bug**
When loading a datapackage.json from disk the output directory field get's replaced with `datapackage.name`.

**To Reproduce**
1. Click "Import metadata ..."
2. Load a datapackage.json

**Expected behavior**
Output directory stays on previous value.

**Desktop (please complete the following information):**
 - Plugin: 0.2.1 (beta release)
 - QGIS 3.18.3
 - Python: 3.8.7
 - OS: macOS 11.4

**Comment by LKajan** [comment]
Hi @n0rdlicht,
I can also reproduce this.
Should the output directory value become the directory of the imported snapshot or just keep it untouched?

**Comment by n0rdlicht** [comment]
> Hi @n0rdlicht,
> I can also reproduce this.
> Should the output directory value become the directory of the imported snapshot or just keep it untouched?

👍 would leave it untouched.

**Comment by LKajan** [comment]
> 👍 would leave it untouched.
Got it
