### ISSUE TITLE
0.1.0 Release

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#6]
Issue to initiate a 0.1.0 plugin release.

- Move to cividi organisation :heavy_check_mark: 
- Renaming to [Spatial Data Package Export](https://github.com/cividi/spatial-data-package-export/issues/4) :heavy_check_mark: 
- Updated changelog
- Add action to publish to QGIS Plugin Repository
- Add Slack Hook to announce releases

**Comment by Joonalai** [comment]
@n0rdlicht any update on this?

**Comment by n0rdlicht** [comment]
done :) Also manually submitted to the QGIS Plugin Repository (https://plugins.qgis.org/plugins/SpatialDataPackageExport/) for approval, hence currently release action and slack message are failing.
