### ISSUE TITLE
Load exported snapshots for editing

### ISSUE THREAD

**Issue by n0rdlicht** [cividi/spatial-data-package-export#8]
**Expected behaviour**
A way to open exported snapshots as QGIS layers and prefilled Spatial Data Package Export fields based on an existing snapshot.json.

**Current behaviour**
Not part of the MVP scope.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Joonalai** [comment]
@n0rdlicht is it possible to add QGIS specific field(s) to the snapshot? One option would be to store the QIGS style specification in that which would make importing of the layers easier (and to avoid using categorized style using feature id).

**Comment by n0rdlicht** [comment]
Thinkable, yes. Would mean that non-QGIS made snapshots would not be importable?

**Comment by Joonalai** [comment]
Good point :thinking:. This has to be investigated further.

**Comment by n0rdlicht** [comment]
After [initial exploration](#46) deferring layer import and focusing on loading metadata from a datapackage.json as a first step.

**Comment by Joonalai** [comment]
Sure thing! We will keep the code but just jump over the layer import.

**Comment by n0rdlicht** [comment]
Created #49 for continuing this in the future ;)
